CREATE TABLE IF NOT EXISTS `Directors` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Actors` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Countries` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Genres` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS `ReleaseYears` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Year` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `Ratings` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS `ShowTypes` (
	`Id` INT PRIMARY KEY NOT NULL,
	`Name` VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Shows` (
	`Id` INT PRIMARY KEY NOT NULL,
	`ShowTypeId` INT NOT NULL,
	`Title` VARCHAR(120) NOT NULL,
	`DateAdded` DATE NULL,
	`ReleaseYearId` INT NOT NULL,
	`RatingId` INT NULL,
	`Duration` VARCHAR(10) NOT NULL,
	`Description` VARCHAR(250) NOT NULL,
	FOREIGN KEY (`ShowTypeId`) REFERENCES `ShowTypes`(`Id`),
	FOREIGN KEY (`ReleaseYearId`) REFERENCES `ReleaseYears`(`Id`),
	FOREIGN KEY (`RatingId`) REFERENCES `Ratings`(`Id`)
);

CREATE TABLE IF NOT EXISTS `ShowDirectors` (
	`Id` INT PRIMARY KEY NOT NULL,
	`ShowId` INT NOT NULL,
	`DirectorId` INT NOT NULL,
	FOREIGN KEY (`ShowId`) REFERENCES `Shows`(`Id`),
	FOREIGN KEY (`DirectorId`) REFERENCES `Directors`(`Id`)
);

CREATE TABLE IF NOT EXISTS `ShowActors` (
	`Id` INT PRIMARY KEY NOT NULL,
	`ShowId` INT NOT NULL,
	`ActorId` INT NOT NULL,
	FOREIGN KEY (`ShowId`) REFERENCES `Shows`(`Id`),
	FOREIGN KEY (`ActorId`) REFERENCES `Actors`(`Id`)
);

CREATE TABLE IF NOT EXISTS `ShowCountries` (
	`Id` INT PRIMARY KEY NOT NULL,
	`ShowId` INT NOT NULL,
	`CountryId` INT NOT NULL,
	FOREIGN KEY (`ShowId`) REFERENCES `Shows`(`Id`),
	FOREIGN KEY (`CountryId`) REFERENCES `Countries`(`Id`)
);

CREATE TABLE IF NOT EXISTS `ShowGenres` (
	`Id` INT PRIMARY KEY NOT NULL,
	`ShowId` INT NOT NULL,
	`GenreId` INT NOT NULL,
	FOREIGN KEY (`ShowId`) REFERENCES `Shows`(`Id`),
	FOREIGN KEY (`GenreId`) REFERENCES `Genres`(`Id`)
);
